name: Tests

on: [push]

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1', 'nightly']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: "Cache artifacts"
        uses: julia-actions/cache@v1
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@latest
      - name: "Run unit tests"
        uses: julia-actions/julia-runtest@latest